#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# precreate log files
for file in /config/log/nginx/access.log /config/log/nginx/error.log; do
    if [[ ! -f "${file}" ]]; then
        touch "${file}"
    fi
done

# copy default config files if they don't exist
if [[ ! -f /config/nginx/ssl.conf ]]; then
    cp /defaults/nginx/ssl.conf.sample /config/nginx/ssl.conf
fi
if [[ ! -f /config/nginx/site-confs/default.conf ]]; then
    cp /defaults/nginx/site-confs/default.conf.sample /config/nginx/site-confs/default.conf
fi

# force nginx.conf to include site-confs/*.conf instead of site-confs/*
sed -i -E "s#^(\s*)include /config/nginx/site-confs/\*;#\1include /config/nginx/site-confs/\*.conf;#" /config/nginx/nginx.conf

# copy index.html if no index file exists
INDEX_EXISTS=false
for file in /config/www/index.*; do
    if [[ -e "${file}" ]]; then
        INDEX_EXISTS=true
        break
    fi
done
if [[ ${INDEX_EXISTS} == false ]] && grep -Eq '^\s*index[^#]*index\.html' /config/nginx/**/*.conf; then
    cp /defaults/www/index.html /config/www/index.html
fi

# copy pre-generated dhparams or generate if needed
if [[ ! -f /config/nginx/dhparams.pem ]]; then
    cp /defaults/nginx/dhparams.pem /config/nginx/dhparams.pem
fi
if ! grep -q 'PARAMETERS' "/config/nginx/dhparams.pem"; then
    curl -o /config/nginx/dhparams.pem -L "https://ssl-config.mozilla.org/ffdhe4096.txt"
fi

# 检测htpasswd文件创建
if [[ ! -f /config/access/.htpasswd ]]; then
    htpasswd -Bb -c /config/access/.htpasswd admin adminadmin
fi

# 检测预配置变量是否存在
if [ ! -n "${preconfigured}" ]
then
    echo "预配置变量数值不存在，默认关闭"
    preconfigured=disable
fi
# 检测是否启用预配置
if [[ "${preconfigured}" == "enable" ]];then
    echo "开启预配置"
    # 检测include目录
    if [[ ! -e /config/nginx/include ]]; then
        cp -r /defaults/nginx/include /config/nginx/
    fi

    # Set resolver, ignore ipv6 addresses
    touch /config/nginx/include/base_config/resolver.conf
    if ! grep -q 'resolver' /config/nginx/include/base_config/resolver.conf; then
        RESOLVERRAW=$(awk 'BEGIN{ORS=" "} $1=="nameserver" {print $2}' /etc/resolv.conf)
        for i in ${RESOLVERRAW}; do
            if [[ "$(awk -F ':' '{print NF-1}' <<<"${i}")" -le 2 ]]; then
                RESOLVER="${RESOLVER} ${i}"
            fi
        done
        if [[ -z "${RESOLVER}" ]]; then
            RESOLVER="127.0.0.11"
        fi
        echo "Setting resolver to ${RESOLVER}"
        RESOLVEROUTPUT="# This file is auto-generated only on first start, based on the container's /etc/resolv.conf file. Feel free to modify it as you wish.\n\nresolver ${RESOLVER} valid=30s;"
        echo -e "${RESOLVEROUTPUT}" >/config/nginx/include/base_config/resolver.conf
    fi
    
    if [[ ! -f /config/nginx/nginx.conf ]]; then
        cp /defaults/nginx/nginx.conf.sample /config/nginx/nginx.conf
    fi

    if [[ ! -f /config/nginx/resolver.conf ]]; then
        echo "include /config/nginx/include/base_config/resolver.conf;" > /config/nginx/resolver.conf
    fi
else
    # Set resolver, ignore ipv6 addresses
    touch /config/nginx/resolver.conf
    if ! grep -q 'resolver' /config/nginx/resolver.conf; then
        RESOLVERRAW=$(awk 'BEGIN{ORS=" "} $1=="nameserver" {print $2}' /etc/resolv.conf)
        for i in ${RESOLVERRAW}; do
            if [[ "$(awk -F ':' '{print NF-1}' <<<"${i}")" -le 2 ]]; then
                RESOLVER="${RESOLVER} ${i}"
            fi
        done
        if [[ -z "${RESOLVER}" ]]; then
            RESOLVER="127.0.0.11"
        fi
        echo "Setting resolver to ${RESOLVER}"
        RESOLVEROUTPUT="# This file is auto-generated only on first start, based on the container's /etc/resolv.conf file. Feel free to modify it as you wish.\n\nresolver ${RESOLVER} valid=30s;"
        echo -e "${RESOLVEROUTPUT}" >/config/nginx/resolver.conf
    fi
    if [[ ! -f /config/nginx/nginx.conf ]]; then
        cp /defaults/nginx/nginx.conf.sample /config/nginx/nginx.conf
        sed -i "s/^\(.*\)\(include \/config\/nginx\/include\/.*\)/\1\#\2/g" /config/nginx/nginx.conf
    fi
    rm /config/nginx/ssl.conf
    cp /defaults/nginx/ssl.conf.special /config/nginx/ssl.conf
fi

# Set worker_processes
touch /config/nginx/worker_processes.conf
if ! grep -q 'worker_processes' /config/nginx/worker_processes.conf; then
    WORKER_PROCESSES=$(nproc)
    echo "Setting worker_processes to ${WORKER_PROCESSES}"
    echo -e "# This file is auto-generated only on first start, based on the cpu cores detected. Feel free to change it to any other number or to auto to let nginx handle it automatically.\n\nworker_processes ${WORKER_PROCESSES};" >/config/nginx/worker_processes.conf
fi