#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
    /config/{keys,www,cache,access,modules} \
    /config/log/{nginx,weblog} \
    /config/nginx/{site-confs,stream,load-modules} \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx
